---

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"

roles:
  - src: https://github.com/agalitsyn/ansible-node.git
    name: agalitsyn.node
    scm: git
    version: master

  - src: https://github.com/agalitsyn/ansible-docker.git
    name: agalitsyn.docker
    scm: git
    version: master
