---

- hosts: all
  gather_facts: False
  become: true
  tasks:
    - name: update package cache
      raw: apt -qqy update

- hosts: all
  become: true
  roles:
    - agalitsyn.node
  tags:
    - node

- hosts: all
  become: true
  roles:
    - agalitsyn.docker
  tags:
    - docker
